#通用配置
server:
  port: 8084 #配置端口
  tomcat.uri-encoding: UTF-8
  #配置项目名
  servlet:
    context-path: /outboundmanage
    session:
      timeout: 1800S
  ##  error: whitelabel: enabled: false

#  compression:
#    enabled: true
#    min-response-size: 1024
#    mime-types:
#      - image/png
#      - image/jpeg
#      - image/jpg
#      - text/html
#      - application/javascript
#      - text/css
#      - application/octet-stream
#      - application/json

spring:
  profiles:
    active: dev #设置开发环境
  devtools:
    restart:
      enabled: true #设置开启热部署
  jmx:
    enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
   # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  #在RedisConfig 配置文件设置过期时间等信息
  redis:
    host: 127.0.0.1 #Redis的主机名
    database: 0    # 使用的数据库（0-15），默认为0
    password: 123456     #redis服务器密码 ,无密码时注销这一行
    port: 6379     #redis的端口号
    ssl: false
    timeout: 20000ms  #Redis连接超时(毫秒）
    jedis:
      pool:
        max-active: 80  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 50    # 连接池中的最大空闲连接
        max-wait: 200ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0     # 连接池中的最小空闲连接
  cache:
    type: redis

logging:
  level:
    com.along.outboundmanage.dao: debug

mybatis:
  mapper-locations: classpath*:com/along/outboundmanage/dao/*Dao.java
  type-aliases-package: com.along.outboundmanage.model
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

netty-websocket:
  host: 0.0.0.0
  path: /netty-websocket
  port: 80


