#开发环境
spring:
  datasource:
    druid:
      driver-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://120.77.175.26:3306/outboundmanage?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 120000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false。
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #启用相应的内置Filter，无法满足要求可另外配置
      filters: stat,wall,logback
      stat-view-servlet:
        #配置监控页面的用户名密码，页面地址http://localhost:8080/druid/index.html
        loginUsername: szgwnet
        loginPassword: 123456
        #配置是否启用监控HTML页面上的“Rest All”功能
        resetEnable: false
